services:
  psql-db:
    image: "postgres:14-bookworm"
    hostname: psql-db
    environment:
      - POSTGRES_PASSWORD=P4ssw0rd
      - POSTGRES_USER=admin
      - POSTGRES_DB=flask_db
      - POSTGRES_HOST_AUTH_METHOD=password
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin" ]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    volumes:
      - ./psql-db.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network

  web:
    build: .
    depends_on:
      psql-db:
        condition: service_healthy
    working_dir: /flask
    ports:
      - "8080:5000"
    networks:
      - app-network

  adminer:
    image: adminer
    restart: always
    networks:
      - app-network
    ports:
      - "8081:8080"

networks:
  app-network:
    driver: bridge
